// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countJobs = `-- name: CountJobs :one
SELECT count(*)
FROM jobs
`

func (q *Queries) CountJobs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countJobs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getJob = `-- name: GetJob :one
SELECT id, source, external_id, url, title, company, location, remote, description, posted_at, created_at, updated_at
FROM jobs
WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id int64) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.Url,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.Remote,
		&i.Description,
		&i.PostedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listJobs = `-- name: ListJobs :many
SELECT id, source, external_id, url, title, company, location, remote, description, posted_at, created_at, updated_at
FROM jobs
ORDER BY posted_at DESC NULLS LAST, id DESC
LIMIT $1 OFFSET $2
`

type ListJobsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.ExternalID,
			&i.Url,
			&i.Title,
			&i.Company,
			&i.Location,
			&i.Remote,
			&i.Description,
			&i.PostedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertJob = `-- name: UpsertJob :one
INSERT INTO jobs (
    source, external_id, url, title, company, location, remote, description, posted_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
ON CONFLICT (source, external_id) DO UPDATE SET
    url         = EXCLUDED.url,
    title       = EXCLUDED.title,
    company     = EXCLUDED.company,
    location    = EXCLUDED.location,
    remote      = EXCLUDED.remote,
    description = EXCLUDED.description,
    posted_at   = EXCLUDED.posted_at,
    updated_at  = now()
RETURNING id, source, external_id, url, title, company, location, remote, description, posted_at, created_at, updated_at
`

type UpsertJobParams struct {
	Source      string             `json:"source"`
	ExternalID  string             `json:"external_id"`
	Url         string             `json:"url"`
	Title       string             `json:"title"`
	Company     string             `json:"company"`
	Location    string             `json:"location"`
	Remote      bool               `json:"remote"`
	Description string             `json:"description"`
	PostedAt    pgtype.Timestamptz `json:"posted_at"`
}

func (q *Queries) UpsertJob(ctx context.Context, arg UpsertJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, upsertJob,
		arg.Source,
		arg.ExternalID,
		arg.Url,
		arg.Title,
		arg.Company,
		arg.Location,
		arg.Remote,
		arg.Description,
		arg.PostedAt,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.Url,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.Remote,
		&i.Description,
		&i.PostedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
