// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const countJobs = `-- name: CountJobs :one
SELECT count(*)
FROM jobs
`

func (q *Queries) CountJobs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countJobs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getJob = `-- name: GetJob :one
SELECT id, source, external_id, url, title, company, location, remote, description, posted_at, created_at, updated_at, company_slug, enrichment, enriched_at, enrichment_version
FROM jobs
WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id int64) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.URL,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.Remote,
		&i.Description,
		&i.PostedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompanySlug,
		&i.Enrichment,
		&i.EnrichedAt,
		&i.EnrichmentVersion,
	)
	return i, err
}

const listJobs = `-- name: ListJobs :many
SELECT id, source, external_id, url, title, company, location, remote, description, posted_at, created_at, updated_at, company_slug, enrichment, enriched_at, enrichment_version
FROM jobs
ORDER BY posted_at DESC NULLS LAST, id DESC
LIMIT $1 OFFSET $2
`

type ListJobsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.ExternalID,
			&i.URL,
			&i.Title,
			&i.Company,
			&i.Location,
			&i.Remote,
			&i.Description,
			&i.PostedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompanySlug,
			&i.Enrichment,
			&i.EnrichedAt,
			&i.EnrichmentVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByCompany = `-- name: ListJobsByCompany :many
SELECT id, source, external_id, url, title, company, location, remote, description, posted_at, created_at, updated_at, company_slug, enrichment, enriched_at, enrichment_version
FROM jobs
WHERE company_slug = $1
ORDER BY posted_at DESC NULLS LAST, id DESC
LIMIT $2 OFFSET $3
`

type ListJobsByCompanyParams struct {
	CompanySlug string `json:"company_slug"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
}

func (q *Queries) ListJobsByCompany(ctx context.Context, arg ListJobsByCompanyParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsByCompany, arg.CompanySlug, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.ExternalID,
			&i.URL,
			&i.Title,
			&i.Company,
			&i.Location,
			&i.Remote,
			&i.Description,
			&i.PostedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompanySlug,
			&i.Enrichment,
			&i.EnrichedAt,
			&i.EnrichmentVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertJob = `-- name: UpsertJob :one
WITH company_upsert AS (
    INSERT INTO companies (slug, name)
    SELECT $6, $5
    WHERE $6 <> ''
    ON CONFLICT (slug) DO UPDATE SET
        name       = EXCLUDED.name,
        updated_at = now()
)
INSERT INTO jobs (
    source, external_id, url, title, company, company_slug, location, remote, description, posted_at,
    enrichment, enriched_at, enrichment_version
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10,
    $11, $12, $13
)
ON CONFLICT (source, external_id) DO UPDATE SET
    url          = EXCLUDED.url,
    title        = EXCLUDED.title,
    company      = EXCLUDED.company,
    company_slug = EXCLUDED.company_slug,
    location     = EXCLUDED.location,
    remote       = EXCLUDED.remote,
    description  = EXCLUDED.description,
    posted_at    = EXCLUDED.posted_at,
    -- Full-replace, consistent with the raw fields above. Seam for phase 2: when
    -- the ingest path (which carries no enrichment) and the enrichment path are
    -- separated, decide whether a source re-ingest preserves existing enrichment.
    enrichment         = EXCLUDED.enrichment,
    enriched_at        = EXCLUDED.enriched_at,
    enrichment_version = EXCLUDED.enrichment_version,
    updated_at   = now()
RETURNING id, source, external_id, url, title, company, location, remote, description, posted_at, created_at, updated_at, company_slug, enrichment, enriched_at, enrichment_version
`

type UpsertJobParams struct {
	Source            string             `json:"source"`
	ExternalID        string             `json:"external_id"`
	URL               string             `json:"url"`
	Title             string             `json:"title"`
	Company           string             `json:"company"`
	CompanySlug       string             `json:"company_slug"`
	Location          string             `json:"location"`
	Remote            bool               `json:"remote"`
	Description       string             `json:"description"`
	PostedAt          pgtype.Timestamptz `json:"posted_at"`
	Enrichment        json.RawMessage    `json:"enrichment"`
	EnrichedAt        pgtype.Timestamptz `json:"enriched_at"`
	EnrichmentVersion int32              `json:"enrichment_version"`
}

// Single atomic write: upsert the company (only when the slug is non-empty,
// via the WHERE on the SELECT) and the job together, keeping the "one write =
// one job" property of the pipeline's write path.
// NOTE: enrichment must be a non-nil json.RawMessage (pass []byte("{}") for an
// un-enriched job, never nil) — the column is NOT NULL and the '{}' default does
// not apply to an explicit NULL on INSERT.
func (q *Queries) UpsertJob(ctx context.Context, arg UpsertJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, upsertJob,
		arg.Source,
		arg.ExternalID,
		arg.URL,
		arg.Title,
		arg.Company,
		arg.CompanySlug,
		arg.Location,
		arg.Remote,
		arg.Description,
		arg.PostedAt,
		arg.Enrichment,
		arg.EnrichedAt,
		arg.EnrichmentVersion,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.URL,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.Remote,
		&i.Description,
		&i.PostedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompanySlug,
		&i.Enrichment,
		&i.EnrichedAt,
		&i.EnrichmentVersion,
	)
	return i, err
}
