// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CountJobs(ctx context.Context) (int64, error)
	GetJob(ctx context.Context, id int64) (Job, error)
	ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error)
	UpsertJob(ctx context.Context, arg UpsertJobParams) (Job, error)
}

var _ Querier = (*Queries)(nil)
