// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_jobs.sql

package db

import (
	"context"
)

const markJobApplied = `-- name: MarkJobApplied :one
INSERT INTO user_jobs (user_id, job_id, applied_at)
VALUES ($1, $2, now())
ON CONFLICT (user_id, job_id) DO UPDATE SET applied_at = now()
RETURNING user_id, job_id, viewed_at, applied_at
`

type MarkJobAppliedParams struct {
	UserID int64 `json:"user_id"`
	JobID  int64 `json:"job_id"`
}

// Mark a job as applied for a user. Idempotent and independent of a prior view:
// it inserts the row (viewed_at defaults) or updates applied_at in place.
func (q *Queries) MarkJobApplied(ctx context.Context, arg MarkJobAppliedParams) (UserJob, error) {
	row := q.db.QueryRow(ctx, markJobApplied, arg.UserID, arg.JobID)
	var i UserJob
	err := row.Scan(
		&i.UserID,
		&i.JobID,
		&i.ViewedAt,
		&i.AppliedAt,
	)
	return i, err
}

const recordJobView = `-- name: RecordJobView :one
INSERT INTO user_jobs (user_id, job_id)
VALUES ($1, $2)
ON CONFLICT (user_id, job_id) DO UPDATE SET viewed_at = now()
RETURNING user_id, job_id, viewed_at, applied_at
`

type RecordJobViewParams struct {
	UserID int64 `json:"user_id"`
	JobID  int64 `json:"job_id"`
}

// Record (or refresh) a user's view of a job. Idempotent on (user_id, job_id):
// the first view creates the row, a repeat view touches viewed_at. Returns the
// row so the caller learns the current applied_at in the same round-trip.
func (q *Queries) RecordJobView(ctx context.Context, arg RecordJobViewParams) (UserJob, error) {
	row := q.db.QueryRow(ctx, recordJobView, arg.UserID, arg.JobID)
	var i UserJob
	err := row.Scan(
		&i.UserID,
		&i.JobID,
		&i.ViewedAt,
		&i.AppliedAt,
	)
	return i, err
}
